### ISSUE TITLE
Shift the template folders from root directory.

### ISSUE THREAD

**Issue by himanshu272** [himanshu272/yt_downloader#8]
The template directory is currently unconventional. Change it so that it isnt in the root directory but the corresponding app directory

**Comment by harshitsurana** [comment]
Do I need to shift the template folder in a new folder in root directory and keep static in the root directory?

**Comment by himanshu272** [comment]
There is a default path at which django checks for the templates if there is no path specified in the settings.py file. Currently the path is specified, look it up. You have to remove that path and shift the templates directory to the default path. Also, did you try to run the program?

**Comment by harshitsurana** [comment]
Is the default path in the app directory(in this case yt_down).
I removed the path and it is working.

**Comment by himanshu272** [comment]
Good. Make a PR

**Comment by harshitsurana** [comment]
I made a PR

**Comment by himanshu272** [comment]
Goog job @harshitsurana :)
